[package]
name = "thread_runner"
version = "0.2.0"
edition = "2021"
description = "A rust library for executing closures concurrently"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"